/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketsEventsRouteImport } from './routes/markets/events'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsIdRouteImport } from './routes/news/$id'
import { Route as NewsSearchRouteImport } from './routes/news/search'
import { Route as PapersIndexRouteImport } from './routes/papers/index'
import { Route as PapersIdRouteImport } from './routes/papers/$id'
import { Route as PapersGraphRouteImport } from './routes/papers/graph'
import { Route as PapersInboxRouteImport } from './routes/papers/inbox'
import { Route as PapersLibraryRouteImport } from './routes/papers/library'
import { Route as NewsTickersSymbolRouteImport } from './routes/news/tickers/$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsEventsRoute = MarketsEventsRouteImport.update({
  id: '/markets/events',
  path: '/markets/events',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSearchRoute = NewsSearchRouteImport.update({
  id: '/news/search',
  path: '/news/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIndexRoute = PapersIndexRouteImport.update({
  id: '/papers/',
  path: '/papers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIdRoute = PapersIdRouteImport.update({
  id: '/papers/$id',
  path: '/papers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersGraphRoute = PapersGraphRouteImport.update({
  id: '/papers/graph',
  path: '/papers/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersInboxRoute = PapersInboxRouteImport.update({
  id: '/papers/inbox',
  path: '/papers/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersLibraryRoute = PapersLibraryRouteImport.update({
  id: '/papers/library',
  path: '/papers/library',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsTickersSymbolRoute = NewsTickersSymbolRouteImport.update({
  id: '/news/tickers/$symbol',
  path: '/news/tickers/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/markets/events': typeof MarketsEventsRoute
  '/news/$id': typeof NewsIdRoute
  '/news/search': typeof NewsSearchRoute
  '/papers/$id': typeof PapersIdRoute
  '/papers/graph': typeof PapersGraphRoute
  '/papers/inbox': typeof PapersInboxRoute
  '/papers/library': typeof PapersLibraryRoute
  '/news/': typeof NewsIndexRoute
  '/papers/': typeof PapersIndexRoute
  '/news/tickers/$symbol': typeof NewsTickersSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/markets/events': typeof MarketsEventsRoute
  '/news/$id': typeof NewsIdRoute
  '/news/search': typeof NewsSearchRoute
  '/papers/$id': typeof PapersIdRoute
  '/papers/graph': typeof PapersGraphRoute
  '/papers/inbox': typeof PapersInboxRoute
  '/papers/library': typeof PapersLibraryRoute
  '/news': typeof NewsIndexRoute
  '/papers': typeof PapersIndexRoute
  '/news/tickers/$symbol': typeof NewsTickersSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/markets/events': typeof MarketsEventsRoute
  '/news/$id': typeof NewsIdRoute
  '/news/search': typeof NewsSearchRoute
  '/papers/$id': typeof PapersIdRoute
  '/papers/graph': typeof PapersGraphRoute
  '/papers/inbox': typeof PapersInboxRoute
  '/papers/library': typeof PapersLibraryRoute
  '/news/': typeof NewsIndexRoute
  '/papers/': typeof PapersIndexRoute
  '/news/tickers/$symbol': typeof NewsTickersSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/login'
    | '/markets/events'
    | '/news/$id'
    | '/news/search'
    | '/papers/$id'
    | '/papers/graph'
    | '/papers/inbox'
    | '/papers/library'
    | '/news/'
    | '/papers/'
    | '/news/tickers/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/login'
    | '/markets/events'
    | '/news/$id'
    | '/news/search'
    | '/papers/$id'
    | '/papers/graph'
    | '/papers/inbox'
    | '/papers/library'
    | '/news'
    | '/papers'
    | '/news/tickers/$symbol'
  id:
    | '__root__'
    | '/'
    | '/consent'
    | '/login'
    | '/markets/events'
    | '/news/$id'
    | '/news/search'
    | '/papers/$id'
    | '/papers/graph'
    | '/papers/inbox'
    | '/papers/library'
    | '/news/'
    | '/papers/'
    | '/news/tickers/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
  MarketsEventsRoute: typeof MarketsEventsRoute
  NewsIdRoute: typeof NewsIdRoute
  NewsSearchRoute: typeof NewsSearchRoute
  PapersIdRoute: typeof PapersIdRoute
  PapersGraphRoute: typeof PapersGraphRoute
  PapersInboxRoute: typeof PapersInboxRoute
  PapersLibraryRoute: typeof PapersLibraryRoute
  NewsIndexRoute: typeof NewsIndexRoute
  PapersIndexRoute: typeof PapersIndexRoute
  NewsTickersSymbolRoute: typeof NewsTickersSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/events': {
      id: '/markets/events'
      path: '/markets/events'
      fullPath: '/markets/events'
      preLoaderRoute: typeof MarketsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/search': {
      id: '/news/search'
      path: '/news/search'
      fullPath: '/news/search'
      preLoaderRoute: typeof NewsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/': {
      id: '/papers/'
      path: '/papers'
      fullPath: '/papers/'
      preLoaderRoute: typeof PapersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$id': {
      id: '/papers/$id'
      path: '/papers/$id'
      fullPath: '/papers/$id'
      preLoaderRoute: typeof PapersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/graph': {
      id: '/papers/graph'
      path: '/papers/graph'
      fullPath: '/papers/graph'
      preLoaderRoute: typeof PapersGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/inbox': {
      id: '/papers/inbox'
      path: '/papers/inbox'
      fullPath: '/papers/inbox'
      preLoaderRoute: typeof PapersInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/library': {
      id: '/papers/library'
      path: '/papers/library'
      fullPath: '/papers/library'
      preLoaderRoute: typeof PapersLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/tickers/$symbol': {
      id: '/news/tickers/$symbol'
      path: '/news/tickers/$symbol'
      fullPath: '/news/tickers/$symbol'
      preLoaderRoute: typeof NewsTickersSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
  MarketsEventsRoute: MarketsEventsRoute,
  NewsIdRoute: NewsIdRoute,
  NewsSearchRoute: NewsSearchRoute,
  PapersIdRoute: PapersIdRoute,
  PapersGraphRoute: PapersGraphRoute,
  PapersInboxRoute: PapersInboxRoute,
  PapersLibraryRoute: PapersLibraryRoute,
  NewsIndexRoute: NewsIndexRoute,
  PapersIndexRoute: PapersIndexRoute,
  NewsTickersSymbolRoute: NewsTickersSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
