/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as MarketsEventsRouteImport } from './routes/markets/events'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsIdRouteImport } from './routes/news/$id'
import { Route as NewsSearchRouteImport } from './routes/news/search'
import { Route as PapersIndexRouteImport } from './routes/papers/index'
import { Route as PapersIdRouteImport } from './routes/papers/$id'
import { Route as PapersGraphRouteImport } from './routes/papers/graph'
import { Route as PapersInboxRouteImport } from './routes/papers/inbox'
import { Route as NewsTickersSymbolRouteImport } from './routes/news/tickers/$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsEventsRoute = MarketsEventsRouteImport.update({
  id: '/markets/events',
  path: '/markets/events',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSearchRoute = NewsSearchRouteImport.update({
  id: '/news/search',
  path: '/news/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIndexRoute = PapersIndexRouteImport.update({
  id: '/papers/',
  path: '/papers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIdRoute = PapersIdRouteImport.update({
  id: '/papers/$id',
  path: '/papers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersGraphRoute = PapersGraphRouteImport.update({
  id: '/papers/graph',
  path: '/papers/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersInboxRoute = PapersInboxRouteImport.update({
  id: '/papers/inbox',
  path: '/papers/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsTickersSymbolRoute = NewsTickersSymbolRouteImport.update({
  id: '/news/tickers/$symbol',
  path: '/news/tickers/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/markets/events': typeof MarketsEventsRoute
  '/news/$id': typeof NewsIdRoute
  '/news/search': typeof NewsSearchRoute
  '/papers/$id': typeof PapersIdRoute
  '/papers/graph': typeof PapersGraphRoute
  '/papers/inbox': typeof PapersInboxRoute
  '/news/': typeof NewsIndexRoute
  '/papers/': typeof PapersIndexRoute
  '/news/tickers/$symbol': typeof NewsTickersSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/markets/events': typeof MarketsEventsRoute
  '/news/$id': typeof NewsIdRoute
  '/news/search': typeof NewsSearchRoute
  '/papers/$id': typeof PapersIdRoute
  '/papers/graph': typeof PapersGraphRoute
  '/papers/inbox': typeof PapersInboxRoute
  '/news': typeof NewsIndexRoute
  '/papers': typeof PapersIndexRoute
  '/news/tickers/$symbol': typeof NewsTickersSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/markets/events': typeof MarketsEventsRoute
  '/news/$id': typeof NewsIdRoute
  '/news/search': typeof NewsSearchRoute
  '/papers/$id': typeof PapersIdRoute
  '/papers/graph': typeof PapersGraphRoute
  '/papers/inbox': typeof PapersInboxRoute
  '/news/': typeof NewsIndexRoute
  '/papers/': typeof PapersIndexRoute
  '/news/tickers/$symbol': typeof NewsTickersSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ops'
    | '/settings'
    | '/watchlist'
    | '/markets/events'
    | '/news/$id'
    | '/news/search'
    | '/papers/$id'
    | '/papers/graph'
    | '/papers/inbox'
    | '/news/'
    | '/papers/'
    | '/news/tickers/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ops'
    | '/settings'
    | '/watchlist'
    | '/markets/events'
    | '/news/$id'
    | '/news/search'
    | '/papers/$id'
    | '/papers/graph'
    | '/papers/inbox'
    | '/news'
    | '/papers'
    | '/news/tickers/$symbol'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/ops'
    | '/settings'
    | '/watchlist'
    | '/markets/events'
    | '/news/$id'
    | '/news/search'
    | '/papers/$id'
    | '/papers/graph'
    | '/papers/inbox'
    | '/news/'
    | '/papers/'
    | '/news/tickers/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRoute
  SettingsRoute: typeof SettingsRoute
  WatchlistRoute: typeof WatchlistRoute
  MarketsEventsRoute: typeof MarketsEventsRoute
  NewsIdRoute: typeof NewsIdRoute
  NewsSearchRoute: typeof NewsSearchRoute
  PapersIdRoute: typeof PapersIdRoute
  PapersGraphRoute: typeof PapersGraphRoute
  PapersInboxRoute: typeof PapersInboxRoute
  NewsIndexRoute: typeof NewsIndexRoute
  PapersIndexRoute: typeof PapersIndexRoute
  NewsTickersSymbolRoute: typeof NewsTickersSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/events': {
      id: '/markets/events'
      path: '/markets/events'
      fullPath: '/markets/events'
      preLoaderRoute: typeof MarketsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/search': {
      id: '/news/search'
      path: '/news/search'
      fullPath: '/news/search'
      preLoaderRoute: typeof NewsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/': {
      id: '/papers/'
      path: '/papers'
      fullPath: '/papers/'
      preLoaderRoute: typeof PapersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$id': {
      id: '/papers/$id'
      path: '/papers/$id'
      fullPath: '/papers/$id'
      preLoaderRoute: typeof PapersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/graph': {
      id: '/papers/graph'
      path: '/papers/graph'
      fullPath: '/papers/graph'
      preLoaderRoute: typeof PapersGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/inbox': {
      id: '/papers/inbox'
      path: '/papers/inbox'
      fullPath: '/papers/inbox'
      preLoaderRoute: typeof PapersInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/tickers/$symbol': {
      id: '/news/tickers/$symbol'
      path: '/news/tickers/$symbol'
      fullPath: '/news/tickers/$symbol'
      preLoaderRoute: typeof NewsTickersSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRoute,
  SettingsRoute: SettingsRoute,
  WatchlistRoute: WatchlistRoute,
  MarketsEventsRoute: MarketsEventsRoute,
  NewsIdRoute: NewsIdRoute,
  NewsSearchRoute: NewsSearchRoute,
  PapersIdRoute: PapersIdRoute,
  PapersGraphRoute: PapersGraphRoute,
  PapersInboxRoute: PapersInboxRoute,
  NewsIndexRoute: NewsIndexRoute,
  PapersIndexRoute: PapersIndexRoute,
  NewsTickersSymbolRoute: NewsTickersSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
