// 图表类型按需注册，进入可视区域才初始化，销毁时释放观察器与画布。
import type { ECharts, EChartsCoreOption } from "echarts/core";
import { useEffect, useRef } from "react";
export function EChart({ option, label, source }: { option: EChartsCoreOption; label: string; source: string }) {
 const ref = useRef<HTMLDivElement>(null);
 useEffect(() => { const element = ref.current; if (!element) return; let chart: ECharts | undefined; let disposed = false; let initializing = false;
 const initialize = async () => { if (chart || initializing) return; initializing = true; const [core, charts, components, renderers] = await Promise.all([import("echarts/core"), import("echarts/charts"), import("echarts/components"), import("echarts/renderers")]); if (disposed) return; core.use([charts.LineChart, charts.BarChart, charts.CandlestickChart, charts.TreemapChart, charts.HeatmapChart, charts.ScatterChart, components.GridComponent, components.TooltipComponent, components.LegendComponent, components.DataZoomComponent, components.VisualMapComponent, renderers.CanvasRenderer]); const tokens = getComputedStyle(element); chart = core.init(element, { textStyle: { color: tokens.getPropertyValue("--text"), fontFamily: tokens.fontFamily }, categoryAxis: { axisLine: { lineStyle: { color: tokens.getPropertyValue("--border") } } } }); chart.setOption(option); };
 const visible = new IntersectionObserver(entries => { if (entries.some(entry => entry.isIntersecting)) void initialize(); }); visible.observe(element); const resize = new ResizeObserver(() => chart?.resize()); resize.observe(element); const scheme = matchMedia("(prefers-color-scheme: dark)"); const theme = () => { chart?.dispose(); chart = undefined; initializing = false; void initialize(); }; scheme.addEventListener("change",theme); const attributes = new MutationObserver(theme); attributes.observe(document.documentElement, { attributes: true, attributeFilter: ["data-theme"] }); return () => { disposed = true; visible.disconnect(); resize.disconnect(); scheme.removeEventListener("change",theme); attributes.disconnect(); chart?.dispose(); }; }, [option]);
 return <figure><div ref={ref} role="img" aria-label={label} style={{ height: 320, width: "100%" }} /><figcaption className="muted">{source}</figcaption></figure>;
}
